In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Check version of numpy libarary

In [ ]:
import numpy as np

print(np.__version__)

1.26.4


Create a NumPy ndarray Object

In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr)

print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


Create a numpy array with a tuple

In [41]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10))

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


**Arrarys**   0-D array

In [ ]:


import numpy as np

arr = np.array(102)

print(arr)

102


1-D array

In [ ]:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

2D array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3D Array

In [42]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**For checking the dimensions of the array**

In [43]:
import numpy as np

a = np.array(102)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(a)
print(b.ndim)
print(b)
print(c.ndim)
print(c)
print(d.ndim)
print(d)


0
102
1
[1 2 3 4 5]
2
[[1 2 3]
 [4 5 6]]
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [44]:

# access elements from 1d array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[2] + arr[3])

# access elements from 2d array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

# access elements from 3d array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

#negative indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


1
7
2nd element on 1st row:  2
6
Last element from 2nd dim:  10


In [ ]:
# 1D Array Slicing

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])    #Slice from the index 3 from the end to index 1 from the end:
print(arr[1:5:2])    #return every other element from index 1 to index 5 with step 2:
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
# 2D Array slicing
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]
[3 8]


In [ ]:
#Datatypes of an array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['Patience', 'Consistency', 'Hardwork'])

print(arr.dtype)
#Create an array with data type 4 bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

#Converting Data Type on Existing Arrays
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

#Converting Data Type on Existing Arrays in bool
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

int64
<U11
[1 2 3 4]
int32
[1 2 3]
int32
[ True False  True]
bool


In [ ]:
# copy() and view()
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


** Shape of Array.** The shape of an array is the number of elements in each dimension.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])   #Print the shape of a 2-D array

print(arr.shape)


# Print the shape of a n-D array

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=3)
print(arr)
print('shape of array :', arr.shape)


(2, 4)
[[[1 2 3 4]]]
shape of array : (1, 1, 4)


Reshaping arrays

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

# 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


# Copy or View
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)      #The example above returns the original array, so it is a view.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6 7 8]


Flattening the arrays


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
# Iterating 1D Arrays
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

# iterating 2D array
  import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

# Iterate on each scalar element of the 2-D array:
  import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)
# Iterate on 3-D array:
    import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)
# Iterate on each scalar element of the 3-D array:
  import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)



1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6


Iterating Arrays Using nditer()

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Numpy Array join

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

# Join two 2-D arrays along rows (axis=1): by default axis is 0

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Joining Arrays Using Stack Functions
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)    # Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

print(arr)


#Stacking Along Rows

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)
#stacking  along Column
arr = np.vstack((arr1, arr2))

print(arr)

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Splitting Numpy Arrays

In [ ]:
# Splitting Numpy Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)    #Split the array in 3 parts

print(newarr)
# Splitting Numpy Arrays in 4 parts
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

#Split the 2-D array into three 2-D arrays.
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)



[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


Searching arrays

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

# find the indexes where the values are even
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


# find the index where the value 9 to be inserted
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.searchsorted(arr, 7)
print(x)

(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)
6


Sorting Array

In [37]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# array alphabetically
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

# boolean array
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

# sort a 2D array
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))



[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


In [39]:
#Array filtering
#Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


#Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[41 43]
[False, False, True, True]
[43 44]
